[env:esp32-s3-devkitc-1-n16r8v]
platform = espressif32
board = esp32-s3-devkitc-1-n16r8v
framework = arduino
monitor_speed = 115200
upload_port = COM8
lib_deps = 
	teemuatlut/TMCStepper@^0.7.3
	waspinator/AccelStepper@^1.64
	easyg0ing1/BlockNot@^2.0.6
	https://github.com/rubegartor/ai-esp32-rotary-encoder.git
	marcoschwartz/LiquidCrystal_I2C@^1.1.4
	br3ttb/PID@^1.2.1
	me-no-dev/AsyncTCP@^1.1.1
	https://github.com/me-no-dev/ESPAsyncWebServer.git
board_build.partitions = no_ota.csv
build_flags = 
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DDEBUG=1
