#define SPI_INTERFACE SPI1

#define PULLER_CS_PIN 10
#define ALIGNER_CS_PIN 9
#define SPOOLER_CS_PIN 8

#define MEASUREMENT_REQ_PIN 24
#define MEASUREMENT_CLK_PIN 23
#define MEASUREMENT_DATA_PIN 22

#define TENSIONER_TRIGGER_PIN 4
#define TENSIONER_ECHO_PIN 5

#define BUZZER_PIN 6